services:
  neurosparkles:
    image: neurosparkles
    build: .

    ports:
      - 80:80
      - 443:443

    depends_on:
      - mongo


  mongo:
    image: mongo

    volumes:
      - ./data/db:/data/db:rw
